# Generated by Django 5.0.1 on 2025-01-04 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcoach',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page.event'),
        ),
    ]
