# Generated by Django 5.0.1 on 2024-12-26 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('page', '0011_remove_occurrence_occurrence_ptr_and_more'),
        ('schedule', '0014_use_autofields_for_pk'),
        ('thelab', '0003_alter_homecalendar_user_alter_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.occurrence')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            bases=('schedule.occurrence',),
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='event',
        ),
        migrations.CreateModel(
            name='EventCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thelab.user')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='page.event')),
            ],
        ),
        migrations.DeleteModel(
            name='AttendeeParent',
        ),
        migrations.DeleteModel(
            name='EventAttendee',
        ),
    ]
