# Generated by Django 5.0 on 2024-06-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_attendeeparent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendee',
            name='user',
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='attendee_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='last_name',
            field=models.CharField(default="(athlete's last name)", help_text="(athlete's last name)", max_length=100),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='first_name',
            field=models.CharField(default="(athlete's first name)", help_text="(athlete's first name)", max_length=50),
        ),
    ]
