# Generated by Django 5.0 on 2024-06-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_eventattendee_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='age',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='first_name',
            field=models.CharField(help_text="(athlete's first name)", max_length=50),
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='last_name',
            field=models.CharField(help_text="(athlete's last name)", max_length=100),
        ),
    ]
