# Generated by Django 5.0 on 2024-05-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventattendee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventattendee',
            name='first_name',
            field=models.CharField(default='(last name)', max_length=100),
        ),
    ]
