# Generated by Django 5.0.1 on 2025-01-04 15:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('thelab', '0002_homecalendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="(athlete's first name)", max_length=50)),
                ('last_name', models.CharField(help_text="(athlete's last name)", max_length=100)),
                ('age', models.IntegerField()),
                ('attendee_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('event_type', models.CharField(choices=[('camp', 'Camp'), ('clinic', 'Clinic'), ('training', 'Training')], max_length=255)),
                ('location_notes', models.CharField(blank=True, help_text="(e.g., 'Field 3', or 'Auxiliary Gym')", max_length=255)),
                ('is_accepted', models.BooleanField(default=True)),
                ('max_attendance', models.IntegerField(default=100)),
            ],
            bases=('schedule.event',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, unique=True)),
                ('location_type', models.CharField(choices=[('in-person', 'In Person'), ('virtual', 'Virtual')], max_length=20)),
                ('hyperlink', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('location_city', models.CharField(blank=True, max_length=255)),
                ('location_state', models.CharField(blank=True, max_length=2)),
                ('location_zip', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='(first name)', max_length=50)),
                ('last_name', models.CharField(default='(last name)', max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(help_text='(Note: locations must be added to your Profile before they can be used in an Event)', on_delete=django.db.models.deletion.CASCADE, to='page.location'),
        ),
        migrations.CreateModel(
            name='CoachLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.location')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('day', models.CharField(choices=[('Wednesday', 'Wednesday'), ('Friday', 'Friday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday')], max_length=10)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page.location')),
            ],
            bases=('schedule.event',),
        ),
        migrations.CreateModel(
            name='PageCalendar',
            fields=[
                ('calendar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.calendar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('schedule.calendar',),
        ),
        migrations.CreateModel(
            name='AttendeeParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.attendee')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.parent')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thelab.profile')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Training', 'Training'), ('P(r)ep Talk', 'P(r)ep Talk')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('athletes', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, help_text='(Note: locations must be added to your Profile before they can be used in a Package)', null=True, on_delete=django.db.models.deletion.CASCADE, to='page.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page.sport')),
            ],
        ),
        migrations.CreateModel(
            name='LocationSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.location')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.sport')),
            ],
        ),
        migrations.CreateModel(
            name='EventSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.event')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.sport')),
            ],
        ),
    ]
