# Generated by Django 5.0.1 on 2025-01-09 01:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="(athlete's first name)", max_length=50)),
                ('last_name', models.CharField(help_text="(athlete's last name)", max_length=100)),
                ('age', models.IntegerField()),
                ('attendee_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday')], max_length=10)),
            ],
            bases=('schedule.event',),
        ),
        migrations.CreateModel(
            name='CoachLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CoachSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.event')),
                ('event_type', models.CharField(choices=[('camp', 'Camp'), ('clinic', 'Clinic'), ('training', 'Training')], max_length=255)),
                ('location_notes', models.CharField(blank=True, help_text="(e.g., 'Field 3', or 'Auxiliary Gym')", max_length=255)),
                ('is_accepted', models.BooleanField(default=True)),
                ('max_attendance', models.IntegerField(default=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='(optional)', max_digits=10, null=True)),
            ],
            bases=('schedule.event',),
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EventSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, unique=True)),
                ('location_type', models.CharField(choices=[('in-person', 'In Person'), ('virtual', 'Virtual')], max_length=20)),
                ('hyperlink', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('location_city', models.CharField(blank=True, max_length=255)),
                ('location_state', models.CharField(blank=True, max_length=2)),
                ('location_zip', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LocationSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('P(r)ep Talk', 'P(r)ep Talk'), ('Training', 'Training')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('athletes', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageCalendar',
            fields=[
                ('calendar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.calendar')),
            ],
            bases=('schedule.calendar',),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='(first name)', max_length=50)),
                ('last_name', models.CharField(default='(last name)', max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendeeParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.attendee')),
            ],
        ),
    ]
