# Generated by Django 5.0.1 on 2024-12-17 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
        ('thelab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesport',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thelab.profile'),
        ),
        migrations.AddField(
            model_name='profilesport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.sport'),
        ),
        migrations.AddField(
            model_name='eventsport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.sport'),
        ),
    ]
