# Generated by Django 5.0.1 on 2025-01-09 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coachlocation',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachsport',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.attendee'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.event'),
        ),
        migrations.AddField(
            model_name='eventsport',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(help_text='(Note: locations must be added to your Profile before they can be used in an Event)', on_delete=django.db.models.deletion.CASCADE, to='page.location'),
        ),
        migrations.AddField(
            model_name='coachlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.location'),
        ),
        migrations.AddField(
            model_name='availability',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page.location'),
        ),
        migrations.AddField(
            model_name='locationsport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.location'),
        ),
        migrations.AddField(
            model_name='package',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.location'),
        ),
        migrations.AddField(
            model_name='package',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagecalendar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendeeparent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.parent'),
        ),
        migrations.AddField(
            model_name='package',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page.sport'),
        ),
        migrations.AddField(
            model_name='locationsport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.sport'),
        ),
        migrations.AddField(
            model_name='eventsport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.sport'),
        ),
        migrations.AddField(
            model_name='coachsport',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.sport'),
        ),
    ]
