# Generated by Django 5.0.1 on 2025-01-07 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(optional)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Sunday', 'Sunday'), ('Saturday', 'Saturday'), ('Friday', 'Friday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.location'),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('P(r)ep Talk', 'P(r)ep Talk'), ('Training', 'Training')], max_length=20),
        ),
    ]
