# Generated by Django 5.0.1 on 2024-12-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('Private Training', 'Private Training'), ('P(r)ep Talk', 'P(r)ep Talk')], max_length=20),
        ),
    ]
