# Generated by Django 5.0.1 on 2025-01-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Wednesday', 'Wednesday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('Training', 'Training'), ('P(r)ep Talk', 'P(r)ep Talk')], max_length=20),
        ),
    ]
