# Generated by Django 5.0 on 2024-08-26 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('p(r)ep_talk', 'P(r)ep Talk'), ('private_training', 'Private Training'), ('clinic', 'Clinic')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, help_text='(Note: locations must be added to your Profile before they can be used in an Event)', on_delete=django.db.models.deletion.CASCADE, to='page.location')),
            ],
        ),
    ]
