# Generated by Django 5.0.1 on 2025-01-10 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_eventattendee_is_accepted_alter_availability_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('P(r)ep Talk', 'P(r)ep Talk'), ('Training', 'Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
