# Generated by Django 5.0 on 2024-08-26 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_package_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='location',
            field=models.ForeignKey(blank=True, help_text='(Note: locations must be added to your Profile before they can be used in an Event)', null=True, on_delete=django.db.models.deletion.CASCADE, to='page.location'),
        ),
        migrations.AlterField(
            model_name='package',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
