# Generated by Django 5.0.1 on 2024-12-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_availability_day_alter_package_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='number_of_sessions',
            new_name='athletes',
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Friday', 'Friday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('Training', 'Training'), ('P(r)ep Talk', 'P(r)ep Talk')], max_length=20),
        ),
    ]
