# Generated by Django 5.0.1 on 2025-01-10 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_parent_user_alter_availability_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_zip',
            new_name='zip',
        ),
        migrations.RemoveField(
            model_name='package',
            name='location',
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Monday', 'Monday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('Training', 'Training'), ('P(r)ep Talk', 'P(r)ep Talk')], max_length=20),
        ),
        migrations.CreateModel(
            name='PackageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.location')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.package')),
            ],
        ),
    ]
