# Generated by Django 5.0 on 2024-08-27 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_package_location_alter_package_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='length',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='package',
            name='number_of_sessions',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='package',
            name='event',
            field=models.CharField(choices=[('private_training', 'Private Training'), ('clinic', 'Clinic'), ('p(r)ep_talk', 'P(r)ep Talk')], max_length=20),
        ),
    ]
