# Generated by Django 5.0.1 on 2025-01-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_rename_location_city_location_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Tuesday', 'Tuesday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Monday', 'Monday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('P(r)ep Talk', 'P(r)ep Talk'), ('Training', 'Training')], max_length=20),
        ),
    ]
