# Generated by Django 5.0 on 2024-08-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_rename_length_package_duration_alter_package_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='event',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('p(r)ep_talk', 'P(r)ep Talk'), ('private_training', 'Private Training')], max_length=20),
        ),
    ]
