# Generated by Django 5.0.1 on 2025-01-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_rename_event_type_event_type_alter_availability_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cached latitude from Google Maps geocoding', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Cached longitude from Google Maps geocoding', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Wednesday', 'Wednesday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('Training', 'Training'), ('P(r)ep Talk', 'P(r)ep Talk')], max_length=20),
        ),
    ]
