# Generated by Django 5.0.1 on 2024-12-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_availability_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Friday', 'Friday'), ('Monday', 'Monday'), ('Wednesday', 'Wednesday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Thursday', 'Thursday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('Training', 'Training'), ('P(r)ep Talk', 'P(r)ep Talk')], max_length=20),
        ),
    ]
