# Generated by Django 5.0 on 2024-08-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_package_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='event',
            field=models.CharField(choices=[('Clinic', 'Clinic'), ('Private Training', 'Private Training'), ('P(r)ep Talk', 'P(r)ep Talk')], max_length=20),
        ),
    ]
