# Generated by Django 5.0.1 on 2025-01-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_location_latitude_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Friday', 'Friday'), ('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday')], max_length=10),
        ),
    ]
