# Generated by Django 5.0.1 on 2024-12-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_availability_day_alter_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Monday', 'Monday')], max_length=10),
        ),
    ]
