# Generated by Django 5.0.1 on 2024-12-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_alter_availability_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Wednesday', 'Wednesday')], max_length=10),
        ),
    ]
