# Generated by Django 5.0.1 on 2024-12-26 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_availability_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='occurrence_ptr',
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="(athlete's first name)", max_length=50)),
                ('last_name', models.CharField(help_text="(athlete's last name)", max_length=100)),
                ('age', models.IntegerField()),
                ('attendee_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendeeParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_first_name', models.CharField(default='(first name)', max_length=50)),
                ('parent_last_name', models.CharField(default='(last name)', max_length=50)),
                ('parent_email', models.EmailField(max_length=50)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.attendee')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.attendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.event')),
            ],
        ),
        migrations.DeleteModel(
            name='EventCoach',
        ),
        migrations.DeleteModel(
            name='Occurrence',
        ),
    ]
