# Generated by Django 5.0 on 2024-12-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_rename_event_package_type_eventcoach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('P(r)ep Talk', 'P(r)ep Talk'), ('Clinic', 'Clinic'), ('Private Training', 'Private Training')], max_length=20),
        ),
    ]
