# Generated by Django 5.0.1 on 2024-12-27 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_remove_occurrence_occurrence_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='page.sport'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Friday', 'Friday'), ('Sunday', 'Sunday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Monday', 'Monday')], max_length=10),
        ),
        migrations.CreateModel(
            name='LocationSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.location')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.sport')),
            ],
        ),
    ]
