# Generated by Django 5.0.1 on 2024-12-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_availability_alter_event_location_notes_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('Clinic', 'Clinic'), ('P(r)ep Talk', 'P(r)ep Talk'), ('Private Training', 'Private Training')], max_length=20),
        ),
    ]
