# Generated by Django 5.0.1 on 2025-01-03 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_package_sport_alter_availability_day_locationsport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Friday', 'Friday'), ('Thursday', 'Thursday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Saturday', 'Saturday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='location',
            field=models.ForeignKey(blank=True, help_text='(Note: locations must be added to your Profile before they can be used in a Package)', null=True, on_delete=django.db.models.deletion.CASCADE, to='page.location'),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('P(r)ep Talk', 'P(r)ep Talk'), ('Training', 'Training')], max_length=20),
        ),
    ]
