# Generated by Django 5.0.1 on 2025-01-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_alter_availability_day_alter_package_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='user',
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Sunday', 'Sunday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday'), ('Thursday', 'Thursday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('Training', 'Training'), ('P(r)ep Talk', 'P(r)ep Talk')], max_length=20),
        ),
    ]
