# Generated by Django 5.0.1 on 2025-01-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0014_remove_attendee_user_alter_availability_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_attendance',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('Friday', 'Friday'), ('Tuesday', 'Tuesday'), ('Monday', 'Monday'), ('Thursday', 'Thursday'), ('Saturday', 'Saturday'), ('Wednesday', 'Wednesday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('P(r)ep Talk', 'P(r)ep Talk'), ('Training', 'Training')], max_length=20),
        ),
    ]
