# Generated by Django 5.0 on 2024-06-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='team',
            field=models.CharField(blank=True, help_text='(i.e., the school or professional organization)', max_length=50),
        ),
    ]
