# Generated by Django 5.0.1 on 2025-01-09 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_use_autofields_for_pk'),
        ('thelab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCalendar',
            fields=[
                ('calendar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.calendar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('schedule.calendar',),
        ),
    ]
