# Generated by Django 5.0.1 on 2024-12-22 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='team',
            field=models.CharField(blank=True, help_text='(i.e., the college/university or professional organization)', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('profile_creation', 'profile_creation'), ('coach_approval', 'coach_approval')], default='profile_creation', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='thelab.user'),
        ),
    ]
