# Generated by Django 5.0.1 on 2025-01-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelab', '0002_homecalendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='roster',
            field=models.TextField(help_text='(Copy-and-paste the link to the roster of any college/professional team on which you are or were a player or a coach)'),
        ),
    ]
