# Generated by Django 5.0.1 on 2025-01-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelab', '0002_homecalendar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='application',
            name='roster',
            field=models.TextField(help_text='(Copy-and-paste the link to a roster of a college/professional team on which you are or were a player or a coach)'),
        ),
    ]
