# Generated by Django 5.0 on 2024-12-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelab', '0002_alter_application_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='control_type',
            field=models.CharField(choices=[('personal', 'personal'), ('parent', 'parent'), ('business', 'business'), ('boss', 'boss')], default='personal', max_length=15),
        ),
    ]
