# Generated by Django 5.0 on 2024-12-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelab', '0003_alter_profileuser_control_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='record',
            new_name='roster',
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD (include the dashes)', null=True),
        ),
    ]
